### PR TITLE
fix #585 add possibility to import Service by string pasting

### LINKED ISSUE #585: cannot import Service from "Import" function
When attempting to import a service, AAC hangs an issue exception 'File Not Found' from DevServicesController.importRealmService

`
reg = yamlObjectMapper.readValue(file.getInputStream(), Service.class);
`

a possibile solution is: 

    if (multiple) {
        Map<String, List<Service>> list = yamlObjectMapper.readValue(yaml, typeRef);
        for (Service reg : list.get(LIST_KEY)) {
            regs.add(reg);
        }
    } else {
        Service reg;
        if (file != null) {
            // try single element from file
            reg = yamlObjectMapper.readValue(file.getInputStream(), Service.class);
        } else {
            // use obj as single element
            reg = yamlObjectMapper.convertValue(obj, Service.class);
        }
        regs.add(reg);
    }

### PR DESCRIPTION
**Pull request by gianpaolo-tndigit**
enable YAML File Import of single service via Import function

### CODE REVIEW

File: src/main/java/it/smartcommunitylab/aac/console/DevServicesController.java [hunk 1]
```diff
@@ -125,8 +125,14 @@ public Collection<Service> importRealmService(
                     regs.add(reg);
                 }
             } else {
-                // try single element
-                Service reg = yamlObjectMapper.readValue(file.getInputStream(), Service.class);
```
Comment (matteo-s) [inline src/main/java/it/smartcommunitylab/aac/console/DevServicesController.java:129]: file is already read into `yaml`, read from it.
